### ISSUE TITLE
Richer README

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/zinnia#53]
- [x] It would be nice if it linked to some Notion pages, for extra context https://github.com/filecoin-station/zinnia/pull/55

The goals of the README should be (imo):
1. [x] Elevator pitch of the project https://github.com/filecoin-station/zinnia/pull/59
2. [x] How to run a rudimentary example https://github.com/filecoin-station/zinnia/pull/54
3. [x] How to create a basic module https://github.com/filecoin-station/zinnia/pull/54
4. [x] How to contribute (either through code, or telling us use cases) https://github.com/filecoin-station/zinnia/pull/55
5. [x] High level project roadmap https://github.com/filecoin-station/zinnia/pull/55

**Comment by juliangruber** [comment]
Via @bajtos:

- README in workspace root - this is the landing page for our GitHub repo. https://github.com/filecoin-station/zinnia
- README for Zinnia CLI crate `zinnia` - this is the landing page on [crates.io](http://crates.io/). https://crates.io/crates/zinnia (sourced from https://github.com/filecoin-station/zinnia/blob/main/cli/README.md)

**Comment by juliangruber** [comment]
> How to create a basic module

@bajtos are we ready to talk about zinnia "modules" yet? Is a module simply a js file with 0-n files it imports from?

**Comment by bajtos** [comment]
> > How to create a basic module
> 
> @bajtos are we ready to talk about zinnia "modules" yet? Is a module simply a js file with 0-n files it imports from?

Yes, I think we are ready.

We don't support module imports yet (see #43), so right now a module is simply a single JS file that implements a long-running process.

I know the missing support for ES Module imports is a poor DX; I'd like to fix it soon after the first public alpha. I propose mentioning #43 in the text explaining that a module must be a single file.
